### model
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora: 2

### dataset
dataset: gommt-oneshot-train
template: llama3 # when using meta-llama model
# template: qwen
cutoff_len: 8192
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/gommt/oneshot-unsloth-micro
logging_steps: 1
save_steps: 5
plot_loss: true
overwrite_output_dir: true
report_to: mlflow

### train
num_train_epochs: 100.0
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
lr_scheduler_type: cosine
warmup_ratio: 0.1
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 5

use_unsloth: true
enable_liger_kernel: true
flash_attn: fa2
rope_scaling: dynamic
