### model
# model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
# quantization_bit: 4
# quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]

### method
stage: sft
do_train: true
finetuning_type: lora
use_dora: true
lora_target: all

### dataset
dataset: gommt-oneshot-train
template: qwen # when using meta-llama model
# template: qwen
cutoff_len: 4096
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
run_name: oneshot-qwen2.5-7B
output_dir: saves/gommt/oneshot-qwen2.5-7B
logging_steps: 1
save_steps: 50
plot_loss: true
overwrite_output_dir: true
report_to: clearml

### train
num_train_epochs: 10.0
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
warmup_steps: 150
save_total_limit: 1 ## change for test

### eval
eval_dataset: gommt-oneshot-val-micro
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 5

use_unsloth: true
enable_liger_kernel: true
flash_attn: fa2
rope_scaling: dynamic
