### model
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
# model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: gommt-full
template: llama3 # when using meta-llama model
# template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/gommt/full
logging_steps: 1
save_steps: 10
plot_loss: true
overwrite_output_dir: true
report_to: mlflow

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10

# use_unsloth: true
# flash_attn: fa2
# rope_scaling: dynamic
# enable_liger_kernel: true